projectName: tenant #多项目的时候模块名
multiple: true #是否多模块项目
templateDir: /template/jpa #代码模块文件夹
entityPackage: com.nbsaas.basic.tenant.data.entity
entities:
  - Domain
  - Member
  - Tenant
  - TenantCatalog
  - TenantDictionary
  - TenantDictionaryItem
outputPath: E:\codes\boot\boot-basic #项目根目录
basePackage: com.nbsaas.basic #基础包名