projectName: trade #多项目的时候模块名
multiple: true #是否多模块项目
templateDir: /template/jpa #代码模块文件夹
entityPackage: com.nbsaas.boot.trade.data.entity
entities:
  - BasicTradeAccount
  - TradeAccount
  - TradeAccountException
  - TradeInfo
  - TradeStream
  - UserTradeAccount
outputPath: E:\codes\nbsaas-starter\nbsaas-boot-starter #项目根目录
basePackage: com.nbsaas.boot #基础包名